services:
  app:
    build: .
    container_name: python-app-server
    command: python -m uvicorn --app-dir ./src app:papp.app --host 0.0.0.0 --port 8000
    ports: 
      - 8000:8000
      - 5678:5678
    volumes:
      - ./src:/app
    depends_on:
      - redis

  redis:
    image: redis:alpine