services:
  app:
    build: .
    container_name: python-app-server
    command: uvicorn app:papp.fastapi_app --host 0.0.0.0 --port 8000 --reload
    ports: 
      - 8000:8000
      - 5678:5678
    volumes:
      - ./src:/app
    depends_on:
      - redis

  redis:
    image: redis:alpine